Django 1.10 support
fusionbox/django-widgy pull request #383
Opened 2017-02-03 18:37 UTC by gavinwahl

2017-02-03 21:07 UTC, nadzinski requested changes

2017-02-03 21:07 UTC, iainwatts commented on widgy/models/base.py
> +        print((self, self.pk), (new, new.pk))
Remove print statement

2017-02-03 21:07 UTC, iainwatts commented on widgy/models/base.py
> +        try:
Add comment to explain what this does?

2017-08-02 11:23 UTC, lockie commented
It would be lovely to have this merged. Anyone?

2019-01-05 08:42 UTC, santoshray02 commented
I am getting this error

django.db.utils.OperationalError: no such table: django_content_type

2019-07-15 22:31 UTC, merged